sudo: required
language: rust
cache: cargo

os:
  - linux

rust:
  - stable
  - nightly

matrix:
  include:
    - name: rustfmt
      rust: nightly-2018-10-30 # We're using unstable rustfmt configuration options
      install: rustup component add rustfmt-preview
      script: cargo fmt --all -- --check
    - name: style
      rust: 1.29.0 # First version to include clippy-preview
      install: rustup component add clippy-preview
      script: cargo clippy --all -- -D warnings
  allow_failures:
    - rust: nightly
  fast_finish: true

addons:
  apt:
    packages:
      - libssl-dev
      - pkg-config
      - cmake
      - zlib1g-dev
git:
  depth: 1
branches:
  only:
    - staging
    - trying
    - master
notifications:
  email: false

before_script: cargo bootstrap

script:
  - |
      cargo build --all --verbose &&
      cargo test --all --verbose &&
      cargo doc --all --verbose

after_success:
  - |
      if [[ $TRAVIS_RUST_VERSION =~ nightly ]]; then
        RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
        cargo tarpaulin --out Xml &&
        bash <(curl -s https://codecov.io/bash)
      fi
