[package]
name = "pest_vm"
description = "pest grammar virtual machine"
version = "2.2.0"
edition = "2018"
authors = ["Drago»ô Tiselice <dragostiselice@gmail.com>"]
homepage = "https://pest-parser.github.io/"
repository = "https://github.com/pest-parser/pest"
documentation = "https://docs.rs/pest"
keywords = ["pest", "vm"]
categories = ["parsing"]
license = "MIT/Apache-2.0"
readme = "_README.md"
rust-version = "1.56"

[dependencies]
pest = { path = "../pest", version = "2.2.0" }
pest_meta = { path = "../meta", version = "2.2.0" }
