[package]
name = "pest_derive"
description = "pest's derive macro"
version = "2.0.0"
authors = ["Drago»ô Tiselice <dragostiselice@gmail.com>"]
repository = "https://github.com/pest-parser/pest"
documentation = "https://docs.rs/pest"
keywords = ["pest", "parser", "peg", "grammar"]
categories = ["parsing"]
license = "MIT/Apache-2.0"
readme = "_README.md"

[lib]
name = "pest_derive"
proc-macro = true

[dependencies]
pest = { path = "../pest", version = "^2.0" }
pest_meta = { path = "../meta", version = "^2.0" }
quote = "^0.4"
syn = "^0.12"

[badges]
codecov = { repository = "pest-parser/pest" }
maintenance = { status = "actively-developed" }
travis-ci = { repository = "pest-parser/pest" }
