[package]
name = "pest"
description = "The Elegant Parser"
version = "1.0.0"
authors = ["Drago»ô Tiselice <dragostiselice@gmail.com>"]
repository = "https://github.com/pest-parser/pest"
documentation = "https://docs.rs/pest"
keywords = ["pest", "parser", "peg", "grammar"]
categories = ["parsing"]
license = "MPL-2.0"
readme = "../README.md"

[dev-dependencies]
pest_grammars = { git = "https://github.com/pest-parser/pest", branch = "procedural" }

[badges]
travis-ci = { repository = "pest-parser/pest" }
