[package]
name = "pest"
description = "The Elegant Parser"
version = "1.0.0-rc.1"
authors = ["Drago»ô Tiselice <dragostiselice@gmail.com>"]
repository = "https://github.com/pest-parser/pest"
documentation = "https://docs.rs/pest"
keywords = ["pest", "parser", "peg", "grammar"]
categories = ["parsing"]
license = "MPL-2.0"
readme = "_README.md"

[badges]
travis-ci = { repository = "pest-parser/pest" }
