[package]
name = "pest_grammars"
description = "pest popular grammar implementations"
version = "1.0.0"
authors = ["Drago»ô Tiselice <dragostiselice@gmail.com>"]
repository = "https://github.com/pest-parser/pest"
documentation = "https://docs.rs/pest"
keywords = ["pest", "parser", "peg", "grammar"]
categories = ["parsing"]
license = "MPL-2.0"
readme = "../README.md"

[dependencies]
#pest = { git = "https://github.com/pest-parser/pest", branch = "procedural" }
pest = { path = "../pest" }
#pest_derive = { git = "https://github.com/pest-parser/pest", branch = "procedural" }
pest_derive = { path = "../pest_derive" }

[badges]
travis-ci = { repository = "pest-parser/pest" }
