name: pest Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish crates on release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write     # Required for OIDC token exchange
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@1.82.0 # needed for `litemap v0.8.0` in pest_debugger
      - name: Bootstraping Grammars - Building
        run: cargo build --package pest_bootstrap
      - name: Bootstraping Grammars - Executing
        run: cargo run --package pest_bootstrap
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - name: Publish pest crates
        run: ./release.sh
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}